using EasyLocalLLM.LLM.Core;
using EasyLocalLLM.LLM.Factory;
using EasyLocalLLM.LLM.Ollama;
using UnityEngine;
using UnityEngine.UIElements;
using System.Collections.Generic;

/// <summary>
/// Lateral thinking quiz game sample
/// An example of a simple chat application combining 4 types of AI.
/// 1) Puzzle master AI (outputs quiz topics)
/// 2) Yes/No AI (answers Yes/No to questions about the quiz)
/// 3) Opponent AI (tries to answer based on Yes/No responses)
/// 4) Judge AI (judges if answers are correct)
/// 
/// When the start button is clicked, the puzzle master AI generates a quiz topic with both "topic" and "truth".
/// The "topic" and "truth" generated by the puzzle master are passed to the Yes/No AI and Judge AI.
/// The "topic" is passed to the opponent AI, which tries to answer but asks the Yes/No AI for more information if needed.
/// The Judge AI judges if the player's or opponent AI's answer is correct, returning "correct" or "incorrect".
/// The game ends when a correct answer is given, and the truth is displayed.
/// 
/// Expected UI components:
/// ・Quiz Generate Button (PuzzleGenerateButton)
/// ・Give Up Button (GiveupButton)
/// ・Topic Display Label (PuzzleLabel)
/// ・Player Question Input Field (PlayerQuestionInput)
/// ・Player Question Send Button (PlayerQuestionSendButton)
/// ・Player Answer Input Field (PlayerAnswerInput)
/// ・Player Answer Send Button (PlayerAnswerSendButton)
/// ・Chat History Display Area (ChatHistory)
/// ・Truth Display Label (TruthLabel)
/// </summary>
public class LateralThinkingQuiz : MonoBehaviour
{
    public UIDocument UIDocument;

    private OllamaClient client;

    // Game Status
    private string currentPuzzle = "";
    private string currentTruth = "";
    private List<string> chatHistory = new();
    private bool isGameActive = false;
    private Coroutine opponentCoroutine;

    // AI Session ID
    private const string JudgeSession = "Judge";

    void Start()
    {
        Debug.Log("=== EasyLocalLLM Lateral Thinking Quiz Game Sample ===");
        InitializeEasyLocalLLMClient();
    }

    void OnDisable()
    {
        RemoveUIEvent();
    }

    private void InitializeEasyLocalLLMClient()
    {
        var config = new OllamaConfig
        {
            ServerUrl = "http://localhost:11434",
            ExecutablePath = Application.streamingAssetsPath + "/Ollama/ollama.exe",
            ModelsDirectory = Application.streamingAssetsPath + "/Ollama/models",
            DefaultModelName = "kamekichi128/qwen3-4b-instruct-2507",
            AutoStartServer = true,
            DebugMode = true,
        };
        OllamaServerManager.Initialize(config, OnOllamaServerInitialized);
        client = LLMClientFactory.CreateOllamaClient(config);
        Debug.Log("✓ Client initialized");
    }

    private void OnOllamaServerInitialized(bool successed)
    {
        if (successed)
        {
            Debug.Log("✓ Ollama server initialized successfully.");
            StartCoroutine(client.LoadModelRunnable(client.GetConfig().DefaultModelName, true, OnModelRunnable));
        }
        else
        {
            Debug.LogError("✗ Failed to initialize Ollama server.");
        }
    }

    private void OnModelRunnable(LoadModelProgress progress)
    {
        if (progress.IsCompleted)
        {
            if (progress.IsSuccessed)
            {
                Debug.Log("✓ Model is runnable.");
                EnableUI();
            }
            else
            {
                Debug.LogError($"✗ Model failed to load: {progress.Message}");
            }
        }
        Debug.Log($"Model loading progress: {progress.Progress * 100}% | {progress.Message}");
    }

    private void EnableUI()
    {
        var root = UIDocument.rootVisualElement;
        var puzzleGenerateButton = root.Q<Button>("PuzzleGenerateButton");
        var playerQuestionSendButton = root.Q<Button>("PlayerQuestionSendButton");
        var playerAnswerSendButton = root.Q<Button>("PlayerAnswerSendButton");
        var giveupButton = root.Q<Button>("GiveupButton");
        var truethLabel = root.Q<Label>("TruthLabel");

        puzzleGenerateButton.clicked += OnPuzzleGenerateClicked;
        playerQuestionSendButton.clicked += OnPlayerQuestionSendClicked;
        playerAnswerSendButton.clicked += OnPlayerAnswerSendClicked;
        giveupButton.clicked += OnGiveupClicked;

        playerQuestionSendButton.SetEnabled(false);
        playerAnswerSendButton.SetEnabled(false);
        giveupButton.SetEnabled(false);
        truethLabel.style.display = DisplayStyle.None;

        OnPuzzleGenerateClicked();
    }

    private void OnGiveupClicked()
    {
        // When player gives up, end the game and show the truth
        GameOver(false);
    }

    private void RemoveUIEvent()
    {
        var root = UIDocument.rootVisualElement;
        var puzzleGenerateButton = root.Q<Button>("PuzzleGenerateButton");
        var playerQuestionSendButton = root.Q<Button>("PlayerQuestionSendButton");
        var playerAnswerSendButton = root.Q<Button>("PlayerAnswerSendButton");
        var giveupButton = root.Q<Button>("GiveupButton");

        puzzleGenerateButton.clicked -= OnPuzzleGenerateClicked;
        playerQuestionSendButton.clicked -= OnPlayerQuestionSendClicked;
        playerAnswerSendButton.clicked -= OnPlayerAnswerSendClicked;
        giveupButton.clicked -= OnGiveupClicked;
    }

    private void OnPuzzleGenerateClicked()
    {
        // Clear sessions
        client.ClearAllMessages();

        // Initialize UI
        var root = UIDocument.rootVisualElement;
        var puzzleGenerateButton = root.Q<Button>("PuzzleGenerateButton");
        var puzzleLabel = root.Q<Label>("PuzzleLabel");
        var truethLabel = root.Q<Label>("TruthLabel");
        var chatHistory = root.Q<Label>("ChatHistory");
        var giveupButton = root.Q<Button>("GiveupButton");

        puzzleGenerateButton.SetEnabled(false);
        puzzleLabel.text = "<Generating Puzzle...>";
        truethLabel.text = "";
        truethLabel.style.display = DisplayStyle.None;
        isGameActive = false;
        this.chatHistory.Clear();


        // Puzzle AI generates "puzzle" and "truth"
        StartCoroutine(client.SendMessageAsync(
            "I want to play a lateral thinking puzzle game.\n\n"
        + "A lateral thinking quiz is a conversational riddle game played between a questioner and participants. \n"
        + "The questioner prepares a “puzzle” and its “truth,” and at the start of the game only the puzzle is presented.\n\n"
        + "The puzzle describes a mysterious situation that cannot be understood from the text alone, and it ends with a short question such as “Why?” or “What happened?”\n"
        + "Here are three examples:\n\n"
        + "Puzzle: A taxi driver was going the wrong way down a one-way street. A police officer on patrol saw him, but did not scold him. Why?\n"
        + "Truth: The taxi driver was not in his car; he was simply walking the wrong way down the one-way street. The one-way rule applies to cars, not pedestrians.\n\n"
        + "Puzzle: A woman went outside on a sunny day and was arrested. Why?\n"
        + "Truth: She was an escaped prisoner. She left the prison, and because it was a clear sunny day, she was easily spotted and arrested.\n\n"
        + "Puzzle: A man without a key was waiting for a woman in front of her house. Moments later, the woman returned and unlocked the door, and the man left immediately. Why?\n"
        + "Truth: The man was a delivery worker. He rang the intercom and waited, but the woman happened to return home, so he handed her the package and left. She had scheduled the delivery for around the same time she expected to get home, but the delivery worker arrived slightly earlier.\n\n"
        + "Please create a new puzzle and truth that are not among the examples above.\n"
        + "Keep both the puzzle and the truth as concise as possible.  Avoid supernatural phenomena, superpowers, and science fiction elements.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error generating puzzle: {error.Message}");
                    puzzleGenerateButton.SetEnabled(true);
                    return;
                }

                if (!response.IsFinal)
                    return;

                // Parse response
                ExtractPuzzleAndTruth(response.Content, out var puzzle, out var truth);
                currentPuzzle = puzzle;
                currentTruth = truth;

                Debug.Log($"Puzzle: {puzzle}");
                Debug.Log($"Truth: {truth}");

                puzzleLabel.text = puzzle;

                this.chatHistory.Clear();
                isGameActive = true;
                AddChatMessage($"[Puzzle Master]\n{puzzle}");

                // Game Start
                var playerQuestionSendButton = root.Q<Button>("PlayerQuestionSendButton");
                var playerAnswerSendButton = root.Q<Button>("PlayerAnswerSendButton");
                var giveupButton = root.Q<Button>("GiveupButton");
                playerQuestionSendButton.SetEnabled(true);
                playerAnswerSendButton.SetEnabled(true);
                giveupButton.SetEnabled(true);

                // Start opponent AI's automatic question and answer loop
                opponentCoroutine = StartCoroutine(OpponentAILoop());
            },
            new ChatRequestOptions
            {
                SystemPrompt = "You are a highly capable puzzle master, both logical and richly imaginative.",
                FormatSchema = new
                {
                    type = "object",
                    properties = new
                    {
                        puzzle = new { type = "string", description = "puzzle" },
                        truth = new { type = "string", description = "truth", maxLength = 1000 },
                    },
                    required = new[] { "puzzle", "truth" }
                },
                WaitIfBusy = true,
                Priority = 75
            }
        ));
    }

    private void OnPlayerQuestionSendClicked()
    {
        var root = UIDocument.rootVisualElement;
        var questionInput = root.Q<TextField>("PlayerQuestionInput");
        string question = questionInput.value;

        if (string.IsNullOrWhiteSpace(question))
            return;

        questionInput.value = "";

        // Send Player Question to Yes/No Answerer AI
        AddChatMessage($"[Player Question]\n{question}");

        StartCoroutine(client.SendMessageAsync(
            $"Puzzle: {currentPuzzle}\nTruth: {currentTruth}\n\nQuestion: {question}\n\nPlease answer briefly with Yes, No, or I don't know.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error: {error.Message}");
                    return;
                }

                if (!response.IsFinal)
                    return;

                AddChatMessage($"[Yes/No Answerer]\n{response.Content}");
            },
            new ChatRequestOptions
            {
                SystemPrompt = "You are a highly logical and capable Yes/No answerer for a puzzle." +
                    "Based on the given truth, answer questions about the truth with Yes, No, or I don't know. Do not provide reasons.",
                Priority = 100,
                WaitIfBusy = true
            }
        ));
    }

    private void AskOpponentAI()
    {
        // Opponent AI attempts to ask questions automatically
        // Include chat history as context and make guesses in a single session
        string chatContext = string.Join("\n", chatHistory);

        StartCoroutine(client.SendMessageAsync(
            $"Chat history so far:\n{chatContext}\n\n" +
            "You are currently playing a game where you read a puzzle and try to answer the truth behind the puzzle. Based on the questions and answers so far, please guess the truth of the puzzle. If you think there is not enough information, ask a new question that can be answered with Yes/No and has not been asked before.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error: {error.Message}");
                    return;
                }

                if (!response.IsFinal)
                    return;

                try
                {
                    var opponentResponse = JsonUtility.FromJson<OpponentResponseData>(response.Content);

                    if (opponentResponse.type == "question")
                    {
                        // Send Question to Yes/No Answerer AI
                        AddChatMessage($"[Opponent]\nQuestion：{opponentResponse.content}");
                        OnYesNoAnswerOpponentQuestion(opponentResponse.content);
                    }
                    else if (opponentResponse.type == "answer")
                    {
                        // Send Answer to Judge AI
                        AddChatMessage($"[Opponent]\nAnswer：{opponentResponse.content}");
                        JudgeOpponentAnswer(opponentResponse.content);
                    }
                }
                catch (System.Exception e)
                {
                    Debug.LogWarning($"Failed to parse opponent response: {e.Message}\nResponse: {response.Content}");
                }
            },
            new ChatRequestOptions
            {
                SystemPrompt = "You are a highly logical and capable opponent in a puzzle game." +
                    "Based on the given puzzle and past questions and answers, logically deduce the truth. Please respond in English.",
                Priority = 50,
                WaitIfBusy = true,
                FormatSchema = new
                {
                    type = "object",
                    properties = new
                    {
                        type = new { type = "string", @enum = new[] { "question", "answer" }, description = "if you want to question, return 'question'; if you want to answer, return 'answer'" },
                        content = new { type = "string", description = "Content of the question or answer" }
                    },
                    required = new[] { "type", "content" }
                }
            }
        ));
    }

    private void OnYesNoAnswerOpponentQuestion(string question)
    {
        // Single session about question from opponent AI
        StartCoroutine(client.SendMessageAsync(
            $"Puzzle: {currentPuzzle}\nTruth: {currentTruth}\n\nQuestion: {question}\n\nPlease answer briefly with Yes, No, or I don't know.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error: {error.Message}");
                    return;
                }

                AddChatMessage($"[Yes/No Answerer (Opponent Query)]\n{response.Content}");
            },
            new ChatRequestOptions
            {
                SystemPrompt = "You are a highly logical and capable Yes/No answerer for a puzzle." +
                    "Based on the given truth, answer questions about the truth with Yes, No, or I don't know. Do not provide reasons.",
                Priority = 100,
                WaitIfBusy = true
            }
        ));
    }


    private void OnPlayerAnswerSendClicked()
    {
        var root = UIDocument.rootVisualElement;
        var answerInput = root.Q<TextField>("PlayerAnswerInput");
        string answer = answerInput.value;

        if (string.IsNullOrWhiteSpace(answer))
            return;

        answerInput.value = "";

        AddChatMessage($"[Player Answer]\n{answer}");

        // Judge answer by Judge AI
        JudgePlayerAnswer(answer);
    }

    private void JudgePlayerAnswer(string answer)
    {
        StartCoroutine(client.SendMessageAsync(
            $"Puzzle: {currentPuzzle}\nTruth: {currentTruth}\n\n" +
            $"Please judge whether the player's answer '{answer}' is correct or not.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error: {error.Message}");
                    return;
                }

                try
                {
                    var judgement = JsonUtility.FromJson<JudgementData>(response.Content);
                    string resultText = judgement.result == "correct" ? "Correct" : "Incorrect";
                    AddChatMessage($"[Judge]\n{resultText}");
                    Debug.Log($"Opponent Answer Judged: {resultText} : {judgement.reason}");

                    if (judgement.result == "correct")
                    {
                        GameOver(true);
                    }
                }
                catch (System.Exception e)
                {
                    Debug.LogWarning($"Failed to parse judge response: {e.Message}\nResponse: {response.Content}");
                }
            },
            new ChatRequestOptions
            {
                SessionId = JudgeSession,
                SystemPrompt = "You are a highly logical and capable judge of correct/incorrect answers for a quiz. Please respond in English.",
                Priority = 100,
                WaitIfBusy = true,
                FormatSchema = new
                {
                    type = "object",
                    properties = new
                    {
                        result = new { type = "string", @enum = new[] { "correct", "incorrect" }, description = "Judgement result. 'correct' if the answer is correct, 'incorrect' otherwise." },
                        reason = new { type = "string", description = "Reason for the judgement" }
                    },
                    required = new[] { "result", "reason" }
                }
            }
        ));
    }

    private void JudgeOpponentAnswer(string opponentAnswer)
    {
        StartCoroutine(client.SendMessageAsync(
            $"Puzzle: {currentPuzzle}\nTruth: {currentTruth}\n\n" +
            $"Please judge whether the opponent AI's answer '{opponentAnswer}' is correct or not.",
            (response, error) =>
            {
                if (error != null)
                {
                    Debug.LogError($"✗ Error: {error.Message}");
                    return;
                }

                if (!response.IsFinal)
                    return;

                try
                {
                    var judgement = JsonUtility.FromJson<JudgementData>(response.Content);
                    string resultText = judgement.result == "correct" ? "Correct" : "Incorrect";
                    AddChatMessage($"[Judge]\n{resultText}");
                    Debug.Log($"Opponent Answer Judged: {resultText} : {judgement.reason}");

                    if (judgement.result == "correct")
                    {
                        GameOver(false);
                    }
                }
                catch (System.Exception e)
                {
                    Debug.LogWarning($"Failed to parse judge response: {e.Message}\nResponse: {response.Content}");
                }
            },
            new ChatRequestOptions
            {
                SessionId = JudgeSession,
                SystemPrompt = "You are a highly logical and capable judge of correct/incorrect answers for a quiz. Please respond in English.",
                Priority = 100,
                WaitIfBusy = true,
                FormatSchema = new
                {
                    type = "object",
                    properties = new
                    {
                        result = new { type = "string", @enum = new[] { "correct", "incorrect" }, description = "Judgement result. 'correct' if the answer is correct, 'incorrect' otherwise." },
                        reason = new { type = "string", description = "Reason for the judgement" }
                    },
                    required = new[] { "result", "reason" }
                }
            }
        ));
    }

    private void GameOver(bool playerWon)
    {
        // End game state and stop Coroutine
        isGameActive = false;
        if (opponentCoroutine != null)
        {
            StopCoroutine(opponentCoroutine);
            opponentCoroutine = null;
        }

        var root = UIDocument.rootVisualElement;
        var truethLabel = root.Q<Label>("TruthLabel");
        var playerQuestionSendButton = root.Q<Button>("PlayerQuestionSendButton");
        var playerAnswerSendButton = root.Q<Button>("PlayerAnswerSendButton");
        var giveupButton = root.Q<Button>("GiveupButton");
        var puzzleGenerateButton = root.Q<Button>("PuzzleGenerateButton");

        playerQuestionSendButton.SetEnabled(false);
        playerAnswerSendButton.SetEnabled(false);
        giveupButton.SetEnabled(false);
        puzzleGenerateButton.SetEnabled(true);
        truethLabel.style.display = DisplayStyle.Flex;

        truethLabel.text = $"【Truth】\n{currentTruth}\n\n{(playerWon ? "Player Wins!" : "Opponent AI Wins!")}";
    }

    private System.Collections.IEnumerator OpponentAILoop()
    {
        // At the start, wait for 10 seconds before first action
        yield return new UnityEngine.WaitForSeconds(10f);

        while (isGameActive)
        {
            Debug.Log("Opponent AI's turn starts");
            AskOpponentAI();

            // Wait for 10 seconds before next action
            yield return new UnityEngine.WaitForSeconds(10f);
        }
    }

    private void AddChatMessage(string message)
    {
        if (isGameActive)
        {
            chatHistory.Add(message);
            UpdateChatHistoryUI();
        }
    }

    private void UpdateChatHistoryUI()
    {
        var root = UIDocument.rootVisualElement;
        var chatHistoryLabel = root.Q<Label>("ChatHistory");
        var invertedHistory = new List<string>(chatHistory);
        invertedHistory.Reverse();
        chatHistoryLabel.text = string.Join("\n\n", invertedHistory);
    }

    private void ExtractPuzzleAndTruth(string response, out string puzzle, out string truth)
    {
        puzzle = "";
        truth = "";

        try
        {
            // Returned in JSON format: {"puzzle": "...", "truth": "..."}
            var data = JsonUtility.FromJson<PuzzleData>(response);
            puzzle = data.puzzle;
            truth = data.truth;
        }
        catch (System.Exception e)
        {
            Debug.LogWarning($"Failed to parse puzzle response: {e.Message}\nResponse: {response}");
        }
    }

    [System.Serializable]
    private class PuzzleData
    {
        public string puzzle;
        public string truth;
    }

    [System.Serializable]
    private class JudgementData
    {
        public string result;
        public string reason;
    }

    [System.Serializable]
    private class OpponentResponseData
    {
        public string type;
        public string content;
    }
}
